### ISSUE TITLE
Missing type or namespace in Unity 2017.3

### ISSUE THREAD

**Issue by IsaiahKelly** [Unity-Technologies/UIElementsExamples#16]
The documentation states: 
> This project is compatible with Unity 2017.3 (currently in alpha).

However, after importing this project into Unity 2017.3.0f3 I receive the following errors:

```
error CS0246: The type or namespace name `IControl' could not be found. Are you missing an assembly reference?
```

```
error CS0246: The type or namespace name `ChangeEvent' could not be found. Are you missing an assembly reference?
```

```
Assertion failed: Assertion failed on expression: 'm_CurrentEntriesPtr != NULL && m_IsGettingEntries'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by Scorr** [comment]
Can we get some more info on this? Will it be added later?

**Comment by IsaiahKelly** [comment]
Oops, looks like I missed this part of the documentation:

> Please use the 2017.2 branch for this project to work with the previous Unity release.

Unfortunately, using that branch in 2017.3.0f3 produces a new error:

```
Assets/Editor/E04_Events.cs(45,31): error CS0305: Using the generic type `UnityEngine.Experimental.UIElements.MouseEventBase<T>' requires `1' type argument(s)
```

The latest master branch `ProjectVersion.txt` file says "2018.1.0a1" and I actually found a [download link to 2018.1.0b1](http://beta.unity3d.com/download/4f520c3a3153/public_download.html), but opening the latest branch in that version still gives the `IControl` missing type or namespace error. I'm guessing this is because of changes since the alpha.

This all leads me to the conclusion that it's probably best to say far away from this experimental feature until it becomes somewhat stable, since it appears that every minor Unity update breaks it!

**Comment by Antoine-Lassauzay** [comment]
I've made the necessary fixes for this compile with both Unity 2017.3 and 2018.1 branches.
